### ISSUE TITLE
No blocked ads / sponsored links

### ISSUE THREAD

**Issue by norman784** [rocketshipapps/adblockfast#1]
## **_Ads**_
- https://auto.mail.ru/article/56816-opel_otzyvaet_v_rossii_krossovery_mokka/
- http://www.imdb.com/news/ni58938529?ref_=hm_nw_tp1
- https://www.google.es/?gws_rd=ssl#q=restaurantes+madrid
- http://www.sohu.com/
- http://news.sohu.com/20150826/n419737748.shtml
- http://www.tianya.cn/
- http://www.sina.com.cn/ - There is ads from AdSame network.
- http://allrecipes.com/Recipe/Chef-Johns-Sloppy-Joes/Detail.aspx?evt19=1&referringHubId=1 - There is a Target ad there, we need to block it
## **_Sponsored links**_
- www.google.es
- www.google.ca
- www.google.it
- www.google.ru
- www.google.in
- http://search.yahoo.co.jp/search?p=toyota&ei=utf-8&fr=news_sw
- http://news.search.yahoo.co.jp/search?p=toyota&ei=utf-8&fr=news_sw

**Comment by wearefaces** [comment]
Any ideas why running  iOS app I can't turn  ads block trough the app? I need to turn it off in the settings and then i can see the text Blocking Ads. BUT no metter what im doing the app wont block ads in safari

**Comment by reneerayking** [comment]
Mute please, I've been hacked
