### ISSUE TITLE
Incompatibility between GPLv3 and App Store

### ISSUE THREAD

**Issue by agh** [rocketshipapps/adblockfast#12]
https://news.ycombinator.com/item?id=10276214

A comment asked for an issue to be raised to discuss and track GPLv3 vs. App Store potential incompatibilities so here we go. An article on [ZDNet](http://www.zdnet.com/article/no-gpl-apps-for-apples-app-store/) gives VLC as an example, and Whisper Systems have [a potential workaround](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#contributor-agreement) to the perceived problem. IANAL. HTH.

**Comment by oldestlivingboy** [comment]
@agh Ty<em>!</em>

**Comment by iliketurtlesbro** [comment]
I believe a license such as the MPL is App Store friendly, but I'd be happiest seeing Adblock Fast remain GPLv3.
