### ISSUE TITLE
ios app install banners are not blocked

### ISSUE THREAD

**Issue by simonvetter** [rocketshipapps/adblockfast#13]
First of all thanks for your awesome work. An open source and free ad blocker for ios app was badly needed :)

I've noticed that app install banners are still showing up on various sites. When tapped, they take the user straight to the app store (which is frustrating and not what you want).
Is there any way to block them? Here's one example:

![image](https://cloud.githubusercontent.com/assets/90988/10103913/ebe01e4c-63a6-11e5-8697-eac1465ddf5c.png)

(That cookie banner is almost as obnoxious but I doubt there's much we can do about it)
Additional (unrelated) question: how is the rule list updated? Are they bundled with fastblock or is the file fetched from github?

**Comment by oldestlivingboy** [comment]
Thanks for the report<em>!</em> Iirc, these banners aren’t injected in page (i.e., we can’t get to them), but I’ll double check.

**Comment by oldestlivingboy** [comment]
Yeah, they’re not in the dom / blockable.
