### ISSUE TITLE
blockerList.json

### ISSUE THREAD

**Issue by tmeisenh** [rocketshipapps/adblockfast#18]
How are you generating blockerList.json for iOS?  I understand the rules are derived from EasyList and Bluhell Firewall but I didn't see anything in the project that builds the ruleset.

**Comment by oldestlivingboy** [comment]
Atm, we have a couple scripts that transform the browser and generate the iOS rulesets. The scripts aren’t included in this project and we’re performance testing new, non-EasyList–based rulesets, so I’m not sure we’d get around to including them before we switch over.

**Comment by tmeisenh** [comment]
Thanks - I was just curious as the lists are the bulk of the content blockers.
