### ISSUE TITLE
[Feature Request] Add country-specific filters

### ISSUE THREAD

**Issue by bzx** [rocketshipapps/adblockfast#19]
It would be great to have country-specific filters, in a similar way it is done in AdBlock, where I can choose a filter list for a specific country/language, except the default EasyList.

**Comment by optikfluffel** [comment]
:+1:

**Comment by xxcriticxx** [comment]
please add Polish Filters 

POL: polskie filtry do Adblocka i uBlocka‎ https://www.certyficate.it/adblock/adblock.txt
Adblock & uBlock polish cookies filters‎ https://www.certyficate.it/adblock/adblock_cookies.txt

**Comment by oldestlivingboy** [comment]
See #17.
