### ISSUE TITLE
Limit permissions the the necessary ones

### ISSUE THREAD

**Issue by yanni858** [rocketshipapps/adblockfast#20]
Among other things, the manifest file asks for "cookies" permissions. 
Is that necessary in order to block ads?

**Comment by oldestlivingboy** [comment]
The permission system in Chrome is pretty busted. If you don’t request at install time a permission that you later find you need, getting the permission becomes nearly impossible. I’ve learned the hard way (https://chrome.google.com/webstore/detail/facebook-disconnect/ejpepffjfmamnambagiibghpglaidiec).
