### ISSUE TITLE
Easier ON/OFF toggle

### ISSUE THREAD

**Issue by caveman1973** [rocketshipapps/adblockfast#21]
When you open the app, you can barely see if the app is working. Would be better to have a big ON and OFF switch instead.

**Comment by caveman1973** [comment]
I forgot to say that's on iOS.

**Comment by oldestlivingboy** [comment]
Thank you for the feedback<em>!</em> Besides the button, there’s a status message in the interface that indicates whether ads are being blocked or not and this is the only mention we’ve gotten about the status being ambiguous, so we won’t fix for now.
