### ISSUE TITLE
The app doesn't load the bundled blockerList.json

### ISSUE THREAD

**Issue by mserougi** [rocketshipapps/adblockfast#26]
I'm having trouble getting the app to function with the bundled blockerList.json file. Basically the app is stuck at "Waiting for permission", and not blocking any ads.

So I added `SFContentBlockerManager:reloadContentBlockerWithIdentifier` to `viewDidLoad`, surely enough that call fails. If I replace blockerList.json file with a simpler one, it loads just fine.

**Comment by oldestlivingboy** [comment]
What are you running ABF on<em>?</em>

**Comment by mserougi** [comment]
I've tried this on an iPhone 6 and 6+.
