### ISSUE TITLE
IOS Build Error

### ISSUE THREAD

**Issue by dodoflying** [rocketshipapps/adblockfast#27]
I got a error when i build IOS version.

"Parse/Parse.h file not found." in file AppDelegate.h . I checked Parse.framework is in the project's linked libraries.

I'm totally new at this. Please advice.

**Comment by oldestlivingboy** [comment]
Our fault<em>!</em> Please pull and try again.

**Comment by oldestlivingboy** [comment]
Duplicate of #24.
