### ISSUE TITLE
7 Rules for Content Blocking?

### ISSUE THREAD

**Issue by ServusJon** [rocketshipapps/adblockfast#35]
When I look at this file (https://github.com/rocketshipapps/adblockfast/blob/master/ios/blocker/blockerList.json) there a more than 7 rules. Is this file normally compressed into 7 rules?

Also I couldn't build it on my device. I couldn't switch the teams…

**Comment by TPS** [comment]
I think the contents of https://github.com/rocketshipapps/adblockfast/blob/master/android/app/src/main/res/raw/blocked.txt (& its clones in the other branches) are the 7 rules.…
