### ISSUE TITLE
Unable to run adblock in iphone 5

### ISSUE THREAD

**Issue by vikashgopalg** [rocketshipapps/adblockfast#38]
iPhone 5 cannot run adblockfast.
adblockfast does not have an architecture that iPhone 5 can execute. 
Kindly help !!

**Comment by norman784** [comment]
> Note: Apps containing content blocking extensions for Safari on iOS are available only on 64-bit devices, due to performance limitations of 32-bit devices.

[check the apple documentation for more information](https://developer.apple.com/library/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html)
