### ISSUE TITLE
New icon shape suggestion

### ISSUE THREAD

**Issue by DO97** [rocketshipapps/adblockfast#42]
Since it is an adblock for samsung browser, why not fit the shape of the icon to the samsung apps?

**Comment by oldestlivingboy** [comment]
Thanks. Could you explain more about what you mean, perhaps with a screenshot.

**Comment by DO97** [comment]
I mean the standard shape of the Samsung apps.
Il 02/Mar/2016 19:48, "Brian Kennish" <notifications@github.com> ha scritto:

**Comment by oldestlivingboy** [comment]
If you mean a rectangle with extra-rounded corners like Samsung uses for their own apps, we’re not Samsung / Adblock Fast isn’t a Samsung app.
