### ISSUE TITLE
switching ON the toggle but it displays the same message "Waiting for permission" after changes in the Bundle Identifier?

### ISSUE THREAD

**Issue by chandananand** [rocketshipapps/adblockfast#46]
When i made the changes in the  Bundle Identifier my app started running in my iPhone 6 plus but even after switching ON the toggle but it displays the same message "Waiting for permission".
I'm not able to find any error can you please suggest why i am facing such issues?

**Comment by chandananand** [comment]
After regular attempt i came to known that the app is using "Bundle Identifier" so i used that in the code and it started running.

**Comment by oldestlivingboy** [comment]
Duplicate of #39.
