### ISSUE TITLE
Switch notifications to big view

### ISSUE THREAD

**Issue by oldestlivingboy** [rocketshipapps/adblockfast#48]
http://developer.android.com/training/notify-user/expanded.html

**Comment by Shinta** [comment]
There is nothing to implement actually, we have to add some lines to decide how and what to show based on the Android Version, this is exactly how we do the notifications for Chrome @oldestlivingboy based on what the browser support.

In the backend we need to send 2 `messages`, and one `title`, then in code we need to check for the version and choose what to use, por example the push data should be:
```json
{
  "title": "This is a title",
  "message": "This is the message",
  "big_message": "This is a biiig message we can send to the phones, this can be a log longer than message"
}
```

We can even have custom buttons according to @rpaszniuk.

This is what I say we should to @oldestlivingboy:
@rpaszniuk can implement the ability to use a big view according to the OS version and if the `push payload` has a `big_message` inside, and we need to code the backend to send 2 versions of text for androids. He can also research how to use those buttons but I think is not going to generate more engagement.

![notifications-bigview](https://cloud.githubusercontent.com/assets/595468/18255412/711fcd38-7377-11e6-8364-b5169c971b33.png)

**Comment by oldestlivingboy** [comment]
Superseded by #65.
