### ISSUE TITLE
confusing README section

### ISSUE THREAD

**Issue by techieshark** [rocketshipapps/adblockfast#54]
Adblock Fast looks great, but I found this section of the README confusing:

> How does Adblock Fast make money?

> Adblock Fast doesn’t, nor do we intend for Adblock Fast to ever, make any money. We operate an (aforementioned) app studio that’s bootstrapped and quite profitable. Yesterday, you probably didn’t know we existed. Today, you do and, someday, perhaps you’ll be creating the next killer app and will consider hiring us. (Hmm, maybe doing good work and shipping good products ought to replace advertising!) Unlike other ad blockers, we don’t have to sell out to support our project.

After reading that, I was looking for the app on the app store and found it for $0.99. Having read the statement above, I then wondered if I was looking at a duplicate app deployed by someone else, but the developer listed in the app store is Rocketship Apps so I am guessing the price changed at some point but the README hasn't been updated.

I'm fine with supporting good apps, especially if they're open source, and charging for it makes it more trustworthy in some ways, and am just pointing out that the README could be updated to prevent future confusion.

Thanks!

**Comment by oldestlivingboy** [comment]
Thank you<em>!</em> We indeed gave Adblock Fast a spin as a paid app for a few months (and may run future monetization experiments) but hadn’t updated that faq – we since have.
