### ISSUE TITLE
Firefox support request

### ISSUE THREAD

**Issue by erotavlas85** [rocketshipapps/adblockfast#62]
Hi,
I found your adblocker, I just wonder to know if you are planning to add firefox support.
Thank you

**Comment by oldestlivingboy** [comment]
I’m sorry for not replying sooner<em>!</em> There’s an open issue, #23, for tracking a Firefox port – we’re more inclined to do the porting now that Firefox supports common extension APIs and the most similar add-on seems to have been sunsetted (https://addons.mozilla.org/en-US/firefox/addon/bluhell-firewall/).
