### ISSUE TITLE
How are the regular expressions used in the Chrome and Opera versions generated?

### ISSUE THREAD

**Issue by Xylobol** [rocketshipapps/adblockfast#70]
Hi!

I'm working on a browser with blocking built in, and I really like how AdBlock Fast works under the hood. I want to reuse this work, but I'd like to add EasyPrivacy. 

I cannot seem to find a way to generate the regular expressions from a filter list. (I'd like to keep using the regex solution because of the performance).

Thank you in advanced!

**Comment by remusao** [comment]
Not meaning to shameless plug here but you might find the discussion in the following issue relevant: https://github.com/rocketshipapps/adblockfast/issues/63

**Comment by oldestlivingboy** [comment]
We haven’t included our filter toolchain (or any server-side software) in this repo – perhaps we will in the future.
