### ISSUE TITLE
ad remaining on french website

### ISSUE THREAD

**Issue by agonist** [rocketshipapps/adblockfast#8]
http://www.leboncoin.fr/ 

Really big unblocked ad here.

**Comment by Shinta** [comment]
Hello @agonist, can you send me the url where I can find it so I can fix this?

**Comment by agonist** [comment]
Hey, the homepage of the website is full of ads and all the other pages too  as you can see on the [screenshot] (http://imgur.com/a/aQlvf)

**Comment by Shinta** [comment]
Oh I see, I think those ads are been displayed with a IP constrain, that's because I'm not seeing them, I will get a French proxy and test it out, thanks @agonist.

**Comment by agonist** [comment]
Hey, same issue here http://www.jeuxvideo.com/ big mac donalds ads. (also a french website)

**Comment by Shinta** [comment]
Ok, will check it out @agonist

**Comment by oldestlivingboy** [comment]
I’m not seeing ads on either site on iOS (so removed label).
