### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by edwinksl** [rocketshipapps/adblockfast#9]
Where can I find the whitelist of websites for which I have turned off Adblock Fast?

**Comment by oldestlivingboy** [comment]
Good news<em>!</em> You’re just six steps away :-P:

In Chrome:

1. choose **Window** > **Extensions**,
2. check the **Developer mode** box,
3. press Adblock Fast’s **background page** link,
4. click the **Resources** tab,
5. choose **Local Storage** > **chrome-extension://…**,
6. view or edit the **whitelist** value, which is a hash of whitelisted domains.

In Opera:

1. choose **View** > **Show Extensions**,
2. press the **Developer Mode** button,
3. press Adblock Fast’s **background page** link,
4. click the **Resources** tab,
5. choose **Local Storage** > **chrome-extension://…**,
6. view or edit the **whitelist** value, which is a hash of whitelisted domains.

**Comment by edwinksl** [comment]
Thanks! Maybe it will be nice to make it more accessible for those who are lazy.

**Comment by dasmurphy** [comment]
Any chance to get whitelisting in iOS?

**Comment by oldestlivingboy** [comment]
@dasmurphy Yeah, most likely in v1.2.

**Comment by dasmurphy** [comment]
Great! :+1:
