### ISSUE TITLE
Google Play Store privacy policy declaration does not match app's privacy policy.

### ISSUE THREAD

**Issue by mxxcon** [rocketshipapps/adblockfast#96]
In Google Play Store you declared:

> * Data safety
> The developer says that this app doesn't collect or share any user data. [Learn more about data safety](https://support.google.com/googleplay?p=data-safety&hl=en)
> 
> * No data shared with third parties
> The developer says this app doesn't share user data with other companies or organizations. [Learn more](https://support.google.com/googleplay?p=data-safety&hl=en) about how developers declare sharing.
> 
> * No data collected
> The developer says this app doesn’t collect user data
> 

![image](https://github.com/rocketshipapps/adblockfast/assets/847140/4788d8f2-d5d1-4293-b323-6742bf429cf5)

<hr>

On your privacy policy website https://www.iubenda.com/privacy-policy/216992 the very 2nd line states:
 > Adblock Fast collects some Personal Data from its Users.

![image](https://github.com/rocketshipapps/adblockfast/assets/847140/e807ddae-9269-46f1-86a4-54adcf945a2d)

And further down the policy you state:

>  Types of Data collected
> 
> Among the types of Personal Data that Adblock Fast collects, by itself or through third parties, there are: email address; Cookies; Usage Data; unique device identifiers for advertising (Google Advertiser ID or IDFA, for example); geographic position; language; first name; last name.

and further down you state:

> How we use the data we collect: sharing of your personal data with third parties
>
> We share your personal data with the third parties listed in detail in the section titled “Detailed information on the processing of Personal Data” within this document. These third parties are grouped and categorized in accordance with the different purposes of processing.

<hr>

So, it appears that your Google Play Store privacy policy declaration is inaccurate and should be updated so that users have a complete and accurate understanding of what this app is doing.

**Comment by oldestlivingboy** [comment]
Thanks, I updated the declaration re analytics data; the other discrepancies are currently accurate:

1. The Iubenda policy covers every Adblock Fast platform target, including the [website](https://adblockfast.com/).
2. Iubenda policies are partly autogenerated so contain some broad language that isn’t necessarily applicable; for example, Adblock Fast for Android uses OneSignal but doesn’t request permission to access Google advertising IDs (and the rest of the data that’s listed seems to apply to web targets, where we don’t use OneSignal at all).
