### ISSUE TITLE
Ads may be unblocked after updating

### ISSUE THREAD

**Issue by oldestlivingboy** [rocketshipapps/adblockfast#97]
Lots of Play reviews complain that ads are no longer blocked following one app update or another, in particular, the update to version 2.1.0. I don’t think any changes should have affected the update behavior, though (Samsung’s spec for ad blockers is at https://developer.samsung.com/internet/android/adblockers-guide.html):

https://github.com/rocketshipapps/adblockfast/compare/a2.0.0...a2.1.0

Other ad blockers have gotten similar complaints, so I suspect that a Samsung Internet bug is causing the controls under the browser’s **Ad blockers** menu item to be nondeterministically reset on receiving an update intent.

**Comment by gmarcus** [comment]
@oldestlivingboy 

Is this specific to Samsung devices only? 

Do you have analytics that shows installs by device? 

Number of ads blocked by device over time?

**Comment by oldestlivingboy** [comment]
@gmarcus There doesn’t seem to be any pattern; AFAICT, here are the devices that all the complaints were posted from:

* Samsung Galaxy S22
* Samsung Galaxy S21 Ultra 5G
* Samsung Galaxy S20 Ultra 5G
* Google Pixel 8
* Google Pixel 7 Pro
* Google Pixel 6 Pro
* Google Pixel 4a
* Xiaomi Redmi Note 12 Pro 5G
* Xiaomi Redmi K20 Pro
* Xiaomi Redmi 6
* OnePlus 7 Pro

**Comment by oldestlivingboy** [comment]
Probably fixed.
